services:
  script:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/code
    env_file:
      - .env
      - .aws/config
      - .aws/credentials

  db:
    image: keinos/sqlite3:latest
    working_dir: /code
    volumes:
      - .:/code
    stdin_open: true
    tty: true
    entrypoint: ["tail", "-f", "/dev/null"]
